<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Student Activity Report</title>
<style>
    @page { margin: 20mm; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 9pt; color: #111; line-height: 1.4; }
    .cover { text-align: center; padding-top: 120px; }
    .cover h1 { font-size: 20pt; color: #2563EB; margin-bottom: 6px; }
    .cover .meta { font-size: 9pt; color: #9CA3AF; margin-top: 20px; }
    .brand { font-size: 8pt; color: #2563EB; margin-top: 40px; letter-spacing: 2px; text-transform: uppercase; }
    .section-title { font-size: 13pt; color: #2563EB; font-weight: bold; border-bottom: 2px solid #2563EB; padding-bottom: 4px; margin-top: 24px; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 8pt; margin-bottom: 12px; }
    th { background-color: #2563EB; color: #fff; padding: 5px 6px; text-align: left; font-size: 7pt; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 4px 6px; border-bottom: 1px solid #E5E7EB; }
    tr:nth-child(even) td { background-color: #F3F4F6; }
    .summary-row td { font-weight: bold; background-color: #EFF6FF !important; border-top: 2px solid #2563EB; }
    .empty-row td { text-align: center; color: #9CA3AF; padding: 16px; font-style: italic; }
    .footer { position: fixed; bottom: 10px; left: 0; right: 0; text-align: center; font-size: 7pt; color: #9CA3AF; border-top: 1px solid #E5E7EB; padding-top: 4px; }
    .page-number:before { content: "Page " counter(page) " of " counter(pages); }
</style>
</head>
<body>

<div class="cover">
    <h1>Student Activity Report</h1>
    <div class="meta">Generated on: {{ $date }}</div>
    <div class="brand">Revisor &mdash; Built by students for students</div>
</div>

<div style="page-break-before: always;">

<h2 class="section-title">All Students</h2>

@if($students->isNotEmpty())
<table>
    <tr>
        <th>Name</th>
        <th>University</th>
        <th style="text-align:center">Subjects</th>
        <th style="text-align:center">Rev. Hours</th>
        <th style="text-align:center">Marks</th>
        <th style="text-align:center">Avg %</th>
        <th>Peer Network</th>
        <th>Last Active</th>
    </tr>
    @foreach($students as $s)
    <tr>
        <td>{{ $s->name }}</td>
        <td>{{ $s->university }}</td>
        <td style="text-align:center">{{ $s->subject_count }}</td>
        <td style="text-align:center">{{ $s->total_hours }}</td>
        <td style="text-align:center">{{ $s->mark_count }}</td>
        <td style="text-align:center">{{ $s->avg_pct !== null ? $s->avg_pct . '%' : 'N/A' }}</td>
        <td>{{ $s->peer_status }}</td>
        <td>{{ $s->last_active }}</td>
    </tr>
    @endforeach
    <tr class="summary-row">
        <td>Total / Avg</td>
        <td>&nbsp;</td>
        <td style="text-align:center">{{ $summary->avg_subjects }} avg</td>
        <td style="text-align:center">{{ $summary->total_hours }}</td>
        <td style="text-align:center">{{ $summary->total_marks }}</td>
        <td style="text-align:center">{{ $summary->avg_pct !== null ? $summary->avg_pct . '%' : 'N/A' }}</td>
        <td>{{ $summary->visible_count }} visible</td>
        <td>&nbsp;</td>
    </tr>
</table>
@else
<table><tr class="empty-row"><td>No students in the system.</td></tr></table>
@endif

</div>

<div class="footer">
    Generated by Revisor &bull; {{ $date }} &bull; Confidential &bull;
    <span class="page-number"></span>
</div>

</body>
</html>
