<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Feedback Report</title>
<style>
    @page { margin: 20mm; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 10pt; color: #111; line-height: 1.5; }
    .cover { text-align: center; padding-top: 120px; }
    .cover h1 { font-size: 20pt; color: #2563EB; margin-bottom: 6px; }
    .cover .meta { font-size: 9pt; color: #9CA3AF; margin-top: 20px; }
    .brand { font-size: 8pt; color: #2563EB; margin-top: 40px; letter-spacing: 2px; text-transform: uppercase; }
    .section-title { font-size: 13pt; color: #2563EB; font-weight: bold; border-bottom: 2px solid #2563EB; padding-bottom: 4px; margin-top: 24px; margin-bottom: 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 9pt; margin-bottom: 12px; }
    th { background-color: #2563EB; color: #fff; padding: 6px 8px; text-align: left; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.5px; }
    td { padding: 5px 8px; border-bottom: 1px solid #E5E7EB; vertical-align: top; }
    tr:nth-child(even) td { background-color: #F3F4F6; }
    .empty-row td { text-align: center; color: #9CA3AF; padding: 16px; font-style: italic; }
    .status-read { color: #6B7280; }
    .status-unread { color: #2563EB; font-weight: bold; }
    .footer { position: fixed; bottom: 10px; left: 0; right: 0; text-align: center; font-size: 7pt; color: #9CA3AF; border-top: 1px solid #E5E7EB; padding-top: 4px; }
    .page-number:before { content: "Page " counter(page) " of " counter(pages); }
</style>
</head>
<body>

<div class="cover">
    <h1>Feedback Report</h1>
    <div class="meta">Generated on: {{ $date }}</div>
    <div class="brand">Revisor &mdash; Built by students for students</div>
</div>

<div style="page-break-before: always;">

<h2 class="section-title">1. Summary</h2>

<table>
    <tr><th style="width:50%">Metric</th><th style="width:50%">Value</th></tr>
    <tr><td>Total Feedback Submissions</td><td>{{ $total }}</td></tr>
    <tr><td>Unread</td><td>{{ $unread }}</td></tr>
</table>

<h3 style="font-size:10pt;color:#2563EB;margin-bottom:8px;">Breakdown by Category</h3>

@if($categoryBreakdown->isNotEmpty())
<table>
    <tr>
        <th>Category</th>
        <th style="text-align:center">Count</th>
        <th style="text-align:center">Percentage</th>
    </tr>
    @foreach($categoryBreakdown as $cb)
    <tr>
        <td>{{ $cb->category ?? 'Uncategorized' }}</td>
        <td style="text-align:center">{{ $cb->count }}</td>
        <td style="text-align:center">{{ $cb->percentage }}%</td>
    </tr>
    @endforeach
</table>
@else
<table><tr class="empty-row"><td>No feedback submissions yet.</td></tr></table>
@endif

<h2 class="section-title">2. All Feedback</h2>

@if($allFeedback->isNotEmpty())
<table>
    <tr>
        <th style="width:22%">Date</th>
        <th style="width:15%">Category</th>
        <th>Message</th>
        <th style="width:12%">Status</th>
    </tr>
    @foreach($allFeedback as $fb)
    <tr>
        <td>{{ $fb->created_at->format('M d, Y g:i A') }}</td>
        <td>{{ $fb->category ?? 'Uncategorized' }}</td>
        <td>{{ $fb->truncated_message }}</td>
        <td class="{{ $fb->is_read ? 'status-read' : 'status-unread' }}">{{ $fb->is_read ? 'Read' : 'Unread' }}</td>
    </tr>
    @endforeach
</table>
@else
<table><tr class="empty-row"><td>No feedback submissions yet.</td></tr></table>
@endif

</div>

<div class="footer">
    Generated by Revisor &bull; {{ $date }} &bull; Confidential &bull;
    <span class="page-number"></span>
</div>

</body>
</html>
